[package]
name = "kaleidoscope"
version = "0.1.0"
authors = ["Leo Balduf <leobalduf@gmail.com>"]
edition = "2018"

[dependencies]
alloy = {git = "https://github.com/mrd0ll4r/alloy"}
#alloy = {path = "../alloy"}
failure = { version = "0.1.7", features = ["std","backtrace"] }
log = { version = "0.4.8", features = ["std","serde"] }
flexi_logger = { version = "0.15.2", features = ["ziplogs"] }
#serde = {version="1.0.104",features=["derive"]}
#serde_json = "1.0.46"
itertools = "0.9.0"

# Tokio, Lua, Runtime
tokio = { version = "0.2.18", features = ["rt-threaded","macros","stream","sync","net","time","tcp"] }
futures = "0.3.4"
interpolation = "0.2.0"
noise = "0.6.0"
rlua = "0.17.0"

# Prometheus
prometheus_exporter = "0.4.1"
prometheus = { version = "0.8.0", features = ["process"] }
lazy_static = "1.4.0"
systemstat = "0.1.5"
